"""Same audit as integrity_check.py, for datasets generated by an older layout.

Two differences from the current dataset layout, both purely path/naming:

1. The SAR label was still spelled "asr" in folder/file names at the time
   (e.g. `ebr-high-asr-high` instead of `ebr-high-sar-high`).
2. There was an extra `evaluation/` folder between the condition folder and
   `pan_0/` (a leftover from a since-removed calibration/evaluation split
   that was always empty on the calibration side, since
   `calibration_files_per_speaker` defaulted to 0):

       ebr-high-asr-high/evaluation/pan_0/p225/spk_p225__p225_001-013_mic1__pan_0__ebr-high-asr-high.flac

Datasets from this era also used the older root folder names --
`OfficeSpeech-EBR-ASR-MONOSPEAKER` and `OfficeSpeech-EBR-ASR-MULTISPEAKER`
(since renamed to SOS-1SP / SOS-2SP) -- though that's just the value you'd
pass as `dataset_path`, not something this module needs to know about.

The actual EBR/SAR values and verification math (SAR via subtraction against
the `ebr-none-asr-none` reference, EBR via cross-correlation + least-squares
unmixing against the bundled source clips) are unchanged and reused directly
from integrity_check.py -- only how paths are found/built differs here.
"""
from pathlib import Path

from ..acoustics import compute_LAeq
from .integrity_check import (
    SAR_TOLERANCE_DB,
    check_sar,
    evaluate_ebr,
    load_channel_first,
    load_source_mono,
)
from .mixing import EBRS, SARS, TARGET_SPEECH_LAEQ

CONDITIONS = [(ebr, sar) for ebr in EBRS for sar in SARS]
REFERENCE_DIR = "ebr-none-asr-none"


def first_n_ids(dataset_root, n):
    clean_root = dataset_root / REFERENCE_DIR / "evaluation" / "pan_0"
    ids = sorted(p.name for p in clean_root.iterdir() if p.is_dir())
    return ids[:n]


def first_m_clean_files(dataset_root, speaker_id, m):
    speaker_dir = dataset_root / REFERENCE_DIR / "evaluation" / "pan_0" / speaker_id
    files = sorted(speaker_dir.glob("*.flac"))
    return files[:m]


def condition_path(clean_path, ebr, sar):
    return Path(str(clean_path).replace(REFERENCE_DIR, f"ebr-{ebr}-asr-{sar}"))


def run(
    dataset_path,
    num_speakers=1,
    num_segments=1,
    events_path="./audio/office_events.wav",
    background_path="./audio/ch01ch04-ooffice-demand.wav",
    check_ebr=False,
):
    """Returns (n_checked, n_failed)."""
    dataset_root = Path(dataset_path)
    if not (dataset_root / REFERENCE_DIR).exists():
        raise FileNotFoundError(
            f"No {REFERENCE_DIR}/ reference folder found under {dataset_root} -- wrong dataset_path, "
            f"or is this actually a current-layout dataset (use integrity_check.py instead)?"
        )

    ids = first_n_ids(dataset_root, num_speakers)
    print(f"Checking {len(ids)} speaker/pair id(s) under {dataset_root}: {ids}\n")

    events_full = events_mono = bg_full = bg_mono = None
    n_checked = 0
    n_failed = 0

    for speaker_id in ids:
        clean_files = first_m_clean_files(dataset_root, speaker_id, num_segments)
        for clean_path in clean_files:
            print(f"=== {speaker_id} / {clean_path.name} ===")
            clean_audio, sr = load_channel_first(clean_path)

            if check_ebr and events_full is None:
                events_full, events_mono = load_source_mono(events_path, sr)
                bg_full, bg_mono = load_source_mono(background_path, sr)

            speech_laeq = compute_LAeq(clean_audio, sr)
            speech_ok = abs(speech_laeq - TARGET_SPEECH_LAEQ) <= SAR_TOLERANCE_DB
            print(f"  clean speech LAeq = {speech_laeq:.2f} dBA (expected ~{TARGET_SPEECH_LAEQ} dBA) "
                  f"[{'OK' if speech_ok else 'UNEXPECTED'}]")

            for ebr_key, sar_key in CONDITIONS:
                noisy_path = condition_path(clean_path, ebr_key, sar_key)
                n_checked += 1
                if not noisy_path.exists():
                    print(f"  ebr-{ebr_key}-asr-{sar_key}: MISSING FILE ({noisy_path})")
                    n_failed += 1
                    continue

                noisy_audio, sr2 = load_channel_first(noisy_path)
                if sr2 != sr or noisy_audio.shape != clean_audio.shape:
                    print(f"  ebr-{ebr_key}-asr-{sar_key}: SHAPE/SR MISMATCH "
                          f"(clean {clean_audio.shape}@{sr} vs noisy {noisy_audio.shape}@{sr2})")
                    n_failed += 1
                    continue

                sar_result = check_sar(clean_audio, noisy_audio, sr, sar_key)
                status = "PASS" if sar_result["pass"] else "FAIL"
                if not sar_result["pass"]:
                    n_failed += 1
                line = (f"  ebr-{ebr_key}-asr-{sar_key}: SAR measured={sar_result['measured_sar']:.2f}dB "
                        f"expected={sar_result['expected_sar']:.2f}dB diff={sar_result['diff']:+.2f}dB [{status}]")

                if check_ebr:
                    y_amb_recovered = noisy_audio - clean_audio
                    ebr_result = evaluate_ebr(
                        y_amb_recovered, sr, events_full, events_mono, bg_full, bg_mono, ebr_key
                    )
                    if ebr_result["pass"] is None:
                        ebr_status = "INCONCLUSIVE"
                    else:
                        ebr_status = "PASS" if ebr_result["pass"] else "FAIL"
                        if not ebr_result["pass"]:
                            n_failed += 1
                    if "measured_ebr" in ebr_result:
                        line += (f" | EBR measured={ebr_result['measured_ebr']:.2f}dB "
                                 f"expected={ebr_result['expected_ebr']:.2f}dB diff={ebr_result['diff']:+.2f}dB "
                                 f"(conf events={ebr_result['conf_events']:.1f} bg={ebr_result['conf_bg']:.1f} "
                                 f"r2={ebr_result['fit_r2']:.2f} events_incr_r2={ebr_result['incremental_r2']:.1e}) [{ebr_status}]")
                    else:
                        line += f" | EBR: {ebr_result['reason']} [INCONCLUSIVE]"

                print(line)
            print()

    print(f"Checked {n_checked} condition files, {n_failed} failed/missing.")
    return n_checked, n_failed
